# Generated by Django 4.1.7 on 2023-03-20 08:00

from django.db import migrations, models
import django.db.models.deletion
import form.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('academic_year', models.CharField(max_length=100)),
                ('admission_date', models.DateField(auto_now_add=True)),
                ('DateofBirthWord', models.TextField()),
                ('BankAcNo', models.IntegerField(max_length=13, null=True)),
                ('IFSCCode', models.CharField(max_length=30, null=True)),
                ('SSSM_ID', models.IntegerField(null=True)),
                ('firstName', models.CharField(blank=True, max_length=20)),
                ('lastName', models.CharField(blank=True, max_length=20)),
                ('fullName', models.CharField(blank=True, max_length=50)),
                ('gender', models.CharField(blank=True, max_length=20)),
                ('dob', models.DateField(blank=True, null=True)),
                ('classSection', models.CharField(blank=True, max_length=20)),
                ('admissionNumber', models.BigIntegerField(primary_key=True, serialize=False)),
                ('mobileNumber', models.BigIntegerField(blank=True, null=True)),
                ('religion', models.CharField(blank=True, max_length=20)),
                ('caste', models.CharField(blank=True, max_length=20)),
                ('tcNumber', models.BigIntegerField(blank=True, null=True)),
                ('aadharNumber', models.BigIntegerField(blank=True, null=True)),
                ('feeWaiverCategory', models.CharField(blank=True, max_length=20)),
                ('siblingID', models.BigIntegerField(blank=True, null=True)),
                ('siblingID0', models.BigIntegerField(blank=True, null=True)),
                ('siblingID1', models.BigIntegerField(blank=True, null=True)),
                ('siblingID2', models.BigIntegerField(blank=True, null=True)),
                ('prevSchoolName', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CurrentAddress',
            fields=[
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='form.studentinfo')),
                ('Address', models.CharField(blank=True, max_length=100)),
                ('Address1', models.CharField(blank=True, max_length=100)),
                ('Address2', models.CharField(blank=True, max_length=100)),
                ('zipCode', models.BigIntegerField(blank=True, null=True)),
                ('state', models.CharField(blank=True, max_length=20)),
                ('city', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='form.studentinfo')),
                ('photo', models.FileField(upload_to=form.models.user_directory_path)),
                ('idProof', models.FileField(upload_to=form.models.user_directory_path)),
                ('castCertificate', models.FileField(upload_to=form.models.user_directory_path)),
                ('domicile', models.FileField(upload_to=form.models.user_directory_path)),
                ('tc', models.FileField(upload_to=form.models.user_directory_path)),
                ('characterCertificate', models.FileField(upload_to=form.models.user_directory_path)),
            ],
        ),
        migrations.CreateModel(
            name='ParentInfo',
            fields=[
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='parent', serialize=False, to='form.studentinfo')),
                ('fatherName', models.CharField(blank=True, max_length=20)),
                ('motherName', models.CharField(blank=True, max_length=20)),
                ('Fatherdob', models.DateField(blank=True, null=True)),
                ('Motherdob', models.DateField(blank=True, null=True)),
                ('MobileNumber', models.BigIntegerField(blank=True, null=True)),
                ('altMobileNumber', models.BigIntegerField(blank=True, null=True)),
                ('gaurdianQual', models.CharField(blank=True, max_length=30)),
                ('guardianOccup', models.CharField(blank=True, max_length=20)),
                ('email', models.CharField(blank=True, max_length=30)),
                ('motherQual', models.CharField(blank=True, max_length=30)),
                ('motherOccup', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PermanentAddress',
            fields=[
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='form.studentinfo')),
                ('Address', models.CharField(blank=True, max_length=100)),
                ('Address1', models.CharField(blank=True, max_length=100)),
                ('Address2', models.CharField(blank=True, max_length=100)),
                ('zipCode', models.BigIntegerField(blank=True, null=True)),
                ('state', models.CharField(blank=True, max_length=20)),
                ('city', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='StudentRoute',
            fields=[
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='form.studentinfo')),
                ('route_code', models.BigIntegerField(blank=True, null=True)),
                ('route_stoppage', models.CharField(blank=True, max_length=30)),
                ('shift', models.CharField(blank=True, max_length=30)),
            ],
        ),
    ]
