# Generated by Django 4.1.7 on 2023-03-20 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classform', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('examName', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ExamType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('examType', models.CharField(max_length=50)),
                ('minMarks', models.IntegerField(default=0)),
                ('maxMarks', models.IntegerField()),
                ('priority', models.IntegerField(blank=True, null=True)),
                ('examName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='markssection.exam')),
            ],
        ),
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50)),
                ('marks', models.IntegerField()),
                ('classroomStudent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classform.classroomstudent')),
                ('examName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='markssection.exam')),
                ('examType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='markssection.examtype')),
            ],
        ),
        migrations.CreateModel(
            name='ExamMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classform.classroom')),
                ('examName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='markssection.exam')),
                ('examType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='markssection.examtype')),
            ],
        ),
        migrations.CreateModel(
            name='AdditionalSubjectMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50)),
                ('marks', models.IntegerField(blank=True, null=True)),
                ('classroomStudent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classform.classroomstudent')),
                ('examName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='markssection.exam')),
                ('examType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='markssection.examtype')),
            ],
        ),
    ]
