# Generated by Django 4.1.7 on 2023-03-20 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classform', '0001_initial'),
        ('employeeform', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassRoomSubjectTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=150)),
                ('class_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classform.classroom')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employeeform.teacher')),
            ],
        ),
    ]
