# Generated by Django 4.1.7 on 2023-03-20 08:00

import classform.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classSection', models.CharField(max_length=50)),
                ('_class', models.CharField(blank=True, max_length=50)),
                ('_section', models.CharField(blank=True, max_length=50)),
                ('class_teacher_alloted', models.BooleanField(default=False)),
                ('room_no', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ClassRoomStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_number', models.IntegerField()),
                ('classRoom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classform.classroom')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='form.studentinfo')),
            ],
        ),
        migrations.CreateModel(
            name='ClassTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_section', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='StudentRouteAttendence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classform.classroomstudent')),
            ],
        ),
        migrations.CreateModel(
            name='ReportCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reportCard', models.FileField(upload_to=classform.models.user_directory_path)),
                ('class_room_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classform.classroomstudent')),
            ],
        ),
    ]
