# Generated by Django 4.1.7 on 2023-03-20 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classform', '0001_initial'),
        ('employeeform', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherAttendence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('available_casual_leave', models.IntegerField(default=10)),
                ('available_sick_leave', models.IntegerField(default=10)),
                ('taken_casual_leave', models.IntegerField(default=0)),
                ('taken_sick_leave', models.IntegerField(default=0)),
                ('total_no_of_days_present', models.IntegerField(default=0)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employeeform.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='StudentAttendence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classform.classroomstudent')),
            ],
        ),
    ]
