# Generated by Django 4.1.7 on 2023-03-20 08:00

from django.db import migrations, models
import django.db.models.deletion
import transport.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employeeform', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('vehicle_no', models.BigIntegerField(primary_key=True, serialize=False)),
                ('device_id', models.BigIntegerField()),
                ('service_id', models.BigIntegerField()),
                ('no_of_seat', models.IntegerField()),
                ('maximum_allowed', models.IntegerField()),
                ('vehicle_type', models.CharField(default='', max_length=30)),
                ('insurance_company', models.CharField(default='', max_length=30)),
                ('contact_person', models.CharField(blank=True, default='', max_length=30)),
                ('insurance_date', models.DateField(blank=True, null=True)),
                ('permit_valid_date', models.DateField(blank=True, null=True)),
                ('pollution_cert_exp_date', models.DateField(blank=True, null=True)),
                ('service_date', models.DateField(blank=True, null=True)),
                ('fitness_service_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Routes',
            fields=[
                ('route_code', models.BigIntegerField()),
                ('start_place', models.CharField(default='', max_length=30)),
                ('end_place', models.CharField(default='', max_length=30)),
                ('shift_time', models.CharField(default='', max_length=30)),
                ('stoppage_names', models.CharField(default='', max_length=100)),
                ('stoppage_id', models.IntegerField(primary_key=True, serialize=False)),
                ('remarks', models.CharField(default='', max_length=50)),
                ('route_distance', models.IntegerField()),
                ('longitude', models.DecimalField(decimal_places=4, max_digits=8)),
                ('lattitude', models.DecimalField(decimal_places=4, max_digits=8)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='employeeform.employee')),
                ('driver_name', models.CharField(default='', max_length=30)),
                ('dob', models.DateField(blank=True, null=True)),
                ('license_no', models.BigIntegerField()),
                ('mobile_no', models.BigIntegerField()),
                ('batch_no', models.BigIntegerField()),
                ('contact_address', models.CharField(default='', max_length=30)),
                ('permanent_address', models.CharField(default='', max_length=30)),
                ('driverPic', models.FileField(upload_to=transport.models.user_directory_path)),
                ('driverLicense', models.FileField(upload_to=transport.models.user_directory_path)),
                ('driverID', models.FileField(upload_to=transport.models.user_directory_path)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.vehicle')),
            ],
        ),
    ]
